name: flutter_advance
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  shared_preferences: ^2.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  accessibility_tools: ^2.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  newrelic_mobile: ^1.1.5
  web_socket_channel: ^3.0.1

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/
    - lib/features/custom_localization/lang/ar.json
    - lib/features/custom_localization/lang/en.json
    - lib/features/custom_localization/lang/fa.json
    - lib/features/custom_localization/lang/hi.json